# Generated by Django 4.1.7 on 2023-03-26 10:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0004_post_tags"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ["publish"]},
        ),
    ]
